# 1) Grab the URL of YOUR Google Sheet and paste Here (make sure it ends with /edit -- clean off anything #gid= and beyond)
google_sheet: https://docs.google.com/spreadsheets/d/17PQQpUwl_uQzQeFrj4gZtQ1BphuhfFf5OYW2Neob-hs/edit

# 2) Give your Jig a name
title: Teh Jigz Up (Jig)

# 3) Change this to you Github user
github_user: teh-jigz-up

# 3) Change this to your repo (when/if you change the name)
github_repo: jig

# 4) This is the header logo, if you want to chnge
header_image: https://teh-jigz-up.github.io/teh-jigz-up/images/teh-jigz-up-header.png

# DO NOT CHANGE
markdown: kramdown

theme: jekyll-theme-cayman